volumes:
  semaphore-mysql:
    name: semaphore-mysql
  traefik_data:
    name: traefik_data
    external: false

networks:
  app_net:
    name: app_net
    external: true
  web_net:
    name: web_net
    external: true

services:
  traefik:
    image: traefik:${image_tag}
    container_name: traefik
    hostname: traefik
    restart: ${restart_policy}
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=web_net"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${acme_email}"
      - "--certificatesresolvers.myresolver.acme.storage=/certs/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "traefik_data:/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.web-auth.basicauth.users=${web_auth_user}:${web_auth_pass}"
      - "traefik.http.routers.http-khodesh.rule=Host(`${TRAEFIK_SUB}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.http-khodesh.entrypoints=web"
      - "traefik.http.routers.khodesh.rule=Host(`${TRAEFIK_SUB}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.khodesh.entrypoints=web-secure"
      - "traefik.http.routers.khodesh.middlewares=web-auth@docker"
      - "traefik.http.routers.khodesh.tls=true"
      - "traefik.http.routers.khodesh.tls.certresolver=myresolver"
      - "traefik.http.services.khodesh.loadBalancer.server.port=8080"

  mysql:
    image: mysql:8.0
    container_name: mysql-semaphore
    hostname: mysql-semaphore
    restart: unless-stopped
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASS}
    networks:
      - app_net

  semaphore:
    restart: unless-stopped
    container_name: semaphore
    hostname: semaphore
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${MYSQL_DB_USER}
      SEMAPHORE_DB_PASS: ${MYSQL_DB_PASS}
      SEMAPHORE_DB_HOST: ${MYSQL_DB_HOST}
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${MYSQL_DB_NAME}
      SEMAPHORE_PLAYBOOK_PATH: /home/semaphore/projects
      SEMAPHORE_ADMIN_PASSWORD: ${SEMA_ADMIN_PASS}
      SEMAPHORE_ADMIN_NAME: ${SEMA_ADMIN_USER}
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      TZ: Asia/Tehran
    depends_on:
      - mysql
    volumes:
      - ./project:/home/semaphore/projects
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.sema.entrypoints=web
      - traefik.http.routers.sema.rule=Host(`${SUB}.${DOMAIN_NAME}`)
      - traefik.http.routers.sema.middlewares=https-redirect
      - traefik.http.routers.sema-secure.entrypoints=web-secure
      - traefik.http.routers.sema.service=sema-secure
      - traefik.http.routers.sema-secure.rule=Host(`${SUB}.${DOMAIN_NAME}`)
      - traefik.http.routers.sema-secure.tls=true
      - traefik.http.routers.sema-secure.tls.options=default
      - traefik.http.routers.sema-secure.service=sema-secure
      - traefik.http.routers.sema-secure.tls.certresolver=mycert
      - traefik.http.services.sema-secure.loadbalancer.server.port=3000